package groovy.practice.interview.preparation.kit.countingValleys

import spock.lang.Specification
import spock.lang.Unroll;

import static practice.interview.preparation.kit.countingValleys.Solution.countingValleys;

class SolutionTest extends Specification {

    @Unroll
    def "testSolution"(String example, int expected) {
        expect:
        expected == countingValleys(example.length(), example)

        where:
        example || expected
        "UDDDUDUU" || 1
        "DDUUDDUDUUUD" || 2
        "DDDUDDUUDUDUUUUDUDUDDDDDDUDUDUDDUDUDDUDDUDUDUUDDDDUDUUUUDDDUUDDDUUDUDDDUDUDDUUDDUUDDUDUDDUDUUUUDDDDDUUUUUUDDUUDDDDDUUDUUDUUUDDDDDUUDDUUUDUUDUUDUDDUDDUDUUUUDUDDUDDUUUDUDUUUUUUDDUUUUDDUUDDUDDUDUDUDUDDDDUDUDDDDDDDDUDUDDUUUUDUUDDDDUDUUUUUDUDUDUDUDUUUDDDDDDDDDDDUUDUUDDUDDUDDUDDUUUUDDUUDDUDDUDDDUDDDUUUDUDUDDUUDUDDUDUUUUUUUDUDDDDDDDDDUUUDUDDDDUUDUUUDUUDUUUUUUDDDUDUUDDDDUUUUDDDUDDDUDDDDUDDUUUDUUDDUDDDUUUDUUDUUUDDUDDDDUUUUUDUDDUDDDUUDDUDUUDDDUUUDDDUUDDDDUDDUDDDUDDUUUUDUUUUUDDUDDDDUUDUUDUUUUDDDDUDUUDDUDDUDDDDUUUDDDDUDUDUDUUUDUUDDDDUUDUUUUDDUUDDUDDUUUUDUUDUDUUDDDUUUDUDUUUUDUDDUUDDUUUUDUUUDUDUUUUDDDDUUDUUDUUUDUDUUDDUUUDDDDUUDUDUUDUUDDUDUDUDUUUUUDDDUUUUDUDUDUUDDDDDUDUUDDUDDUDDDDUUDUDUDUUUUUUUDUUUUUUUDUUUUUUUDDDDUUDUUUUDUUDUDUUUDUUDUUDUDDDUUDUDDUDUDDDUDDUUUUDDUDDDDDUDUDDDDUUDUDUUDDDUDDDDUUUUUDDUUDDDDUDDDDDDUUDUUDUUUUDUUUUDUUUDUDDDUDUUUDUUUUDUUUUUUUUUDDDUDDUUUDUDUDDDUDDUUUUDUUDDDUDDUDUDDDUUDDUUUUUUUUUDDDDUUUUDDDUDDDUUUDUDDDDUUUUDUUDUDUUDDUUDDDUDDUUDDUUUUDDDDDUUUUUUDDUUUDDDUDDDUUUUUDDDUDUDDDDDDUUDUDUUDUDUUUUDUUUUUUUU" || 5
    }

}